name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '30 3 * * *'

jobs:
  create_builds:
    runs-on: namespace-profile-default
    steps:
    - uses: zisismaras/marlin_auto_build@master
